parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     symfony
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    s3_bucket_name: testBucket
    s3_bucket_path: https://s3.amazonaws.com/

    putio_files_path:   /tmp/putio/
    putio_root_folder_id: 12345

    video_thumbnail_interval_seconds: 30

    mixpanel_token: 1234
